"""empty message

Revision ID: 0dd6d1300b1e
Revises: 4704609bef83
Create Date: 2020-06-18 11:07:40.176586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd6d1300b1e'
down_revision = '4704609bef83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    op.add_column('students', sa.Column('student', sa.String(), nullable=False))
    op.add_column('students', sa.Column('timetable_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'timetable', ['timetable_id'], ['id'], ondelete='cascade')
    op.drop_column('students', 'email')
    op.add_column('timetable', sa.Column('signup_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable', 'signup_time')
    op.add_column('students', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'timetable_id')
    op.drop_column('students', 'student')
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='subjects_class_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subjects_pkey')
    )
    # ### end Alembic commands ###
