"""empty message

Revision ID: 464f47fba64c
Revises: 6e8996c6e07a
Create Date: 2020-07-18 16:26:04.892540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464f47fba64c'
down_revision = '6e8996c6e07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('studio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable', 'studio')
    # ### end Alembic commands ###
