"""empty message

Revision ID: 6e8996c6e07a
Revises: b5933bdba889
Create Date: 2020-07-18 15:42:08.298775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8996c6e07a'
down_revision = 'b5933bdba889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('studio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable', 'studio')
    # ### end Alembic commands ###
