"""empty message

Revision ID: 749ce0ede996
Revises: 0dd6d1300b1e
Create Date: 2020-07-07 12:37:02.534212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749ce0ede996'
down_revision = '0dd6d1300b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('revision', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'revision')
    # ### end Alembic commands ###
