"""empty message

Revision ID: 7eef106c05a8
Revises: 
Create Date: 2020-05-30 09:25:12.706938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence


# revision identifiers, used by Alembic.
revision = '7eef106c05a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # op.drop_table('SEQUENCE')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('educations', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('sub_categories', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('systems', sa.Column('rank', sa.Integer(), nullable=True))

    # op.execute(CreateSequence(Sequence('table_id_seq')))
    op.alter_column("systems", "rank", server_default=sa.text("nextval('table_id_seq'::regclass)"))
    op.alter_column("educations", "rank", server_default=sa.text("nextval('table_id_seq'::regclass)"))
    op.alter_column("sub_categories", "rank", server_default=sa.text("nextval('table_id_seq'::regclass)"))
    op.alter_column("classes", "rank", server_default=sa.text("nextval('table_id_seq'::regclass)"))
    op.alter_column("categories", "rank", server_default=sa.text("nextval('table_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'rank')
    op.drop_column('sub_categories', 'rank')
    op.drop_column('educations', 'rank')
    op.drop_column('classes', 'rank')
    op.drop_column('categories', 'rank')
    # ### end Alembic commands ###
