"""empty message

Revision ID: 7f560d68233d
Revises: 861e1f902056
Create Date: 2020-06-15 02:31:33.886676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f560d68233d'
down_revision = '861e1f902056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable', 'link')
    # ### end Alembic commands ###
