"""empty message

Revision ID: 8e17d9c049f6
Revises: e67aeec39ba0
Create Date: 2020-07-17 02:51:38.243709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e17d9c049f6'
down_revision = 'e67aeec39ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('exam_id', sa.Integer(), nullable=True))
    op.add_column('timetable', sa.Column('exam_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timetable', 'exams', ['exam_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'timetable', 'exam_type', ['exam_type_id'], ['id'], ondelete='cascade')
    op.add_column('videos', sa.Column('exam_id', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('exam_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'videos', 'exams', ['exam_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'videos', 'exam_type', ['exam_type_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'exam_type_id')
    op.drop_column('videos', 'exam_id')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_column('timetable', 'exam_type_id')
    op.drop_column('timetable', 'exam_id')
    # ### end Alembic commands ###
