"""empty message

Revision ID: b50bca001cf2
Revises: 7f560d68233d
Create Date: 2020-06-16 06:20:19.095855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50bca001cf2'
down_revision = '7f560d68233d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable', 'accepted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable', sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
