"""empty message

Revision ID: b5933bdba889
Revises: 8e17d9c049f6
Create Date: 2020-07-17 11:21:49.582582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5933bdba889'
down_revision = '8e17d9c049f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'revision')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('revision', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
